import { ReactNode } from 'react';
import { redirect } from 'next/navigation';
import { createClient } from '@/utlis/supabase/server'
import { Metadata } from 'next';

export const metadata:Metadata = {
  title: 'Dashboard - Solid Templates',
  description: 'Generated by Next.js',
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const supabase = createClient()

  const { data, error } = await supabase.auth.getUser()
  if (error || !data?.user) {
    return redirect('/auth/signin?message=' + encodeURIComponent('Please log in your credentials.') + '&type=error');
  }

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
