import { ReactNode } from 'react';
import { redirect } from 'next/navigation';
import { createClient } from '@/utlis/supabase/server'
import { Metadata } from 'next';
import "../globals.css";
import Sidebar from '@/components/Layout/Sidebar';
import Navbar from '@/components/Layout/Navbar';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata:Metadata = {
  title: 'Dashboard - Solid Templates',
  description: 'Generated by Next.js',
};

export default async function DashboardLayout({ children }: { children: ReactNode }) {
  const supabase = createClient()

  const { data, error } = await supabase.auth.getUser()
  if (error || !data?.user) {
    return redirect('/auth/signin?message=' + encodeURIComponent('Please log in your credentials.') + '&type=error');
  }

  return (
    <html lang='en'>
      <body className={`flex ${poppins.className}`}>
        <Sidebar />
        <div className="mx-auto lg:ml-24 w-full">
        <Navbar />
        {children}
        </div>
      </body>
    </html>
  )
}
